
services:
  prefect:
    build: .
    container_name: prefect_etl
    volumes:
      - ./app:/app
    ports:
      - "4200:4200" # Port pour l'interface Prefect si besoin
    environment:
      - PREFECT_API_URL=http://localhost:4200
    command: ["prefect", "server", "start", "--host", "0.0.0.0"]

