services:
  prefect:
    build: .
    container_name: prefect_etl
    volumes:
      - ./src:/app
      - .env:/app/.env
    ports:
      - "4200:4200"
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}